### ISSUE TITLE
Is this project an implement of this paper? 

### ISSUE THREAD

**Issue by UW-Lava** [ssharkov03/Vascular-Deformation-Mapping#1]
Vascular Deformation Mapping (VDM) of Thoracic Aortic Enlargement in Aneurysmal Disease and Dissection
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5675573/ 

If so, can you provide more detail about the usage? thanks a lot

**Comment by ssharkov03** [comment]
I'm sorry to inform you, but it is not implementation of this paper. This code is a part of Novosibirsk State University project aimed at finding deformation field of aorta using Neural Networks (VoxelMorph + Custom Unet in particular). If you are interested, you can ask https://t.me/Yana_Fedotova for more information.
